//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxPreparerSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparerNote
    {
        public int Id { get; set; }
        public int PreparerId { get; set; }
        public int UserId { get; set; }
        public string Notes { get; set; }
        public string Date { get; set; }
        public int Year { get; set; }
        public int NoteCreatorId { get; set; }
    
        public virtual TaxPreparer TaxPreparer { get; set; }
        public virtual TaxPreparer TaxPreparer1 { get; set; }
        public virtual User User { get; set; }
    }
}
