//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxPreparerSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxEntities : DbContext
    {
        public TaxEntities()
            : base("name=TaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User1099> User1099 { get; set; }
        public virtual DbSet<UserMiscDoc> UserMiscDocs { get; set; }
        public virtual DbSet<UserPerDiem> UserPerDiems { get; set; }
        public virtual DbSet<UserToPreparer> UserToPreparers { get; set; }
        public virtual DbSet<UserW2> UserW2 { get; set; }
        public virtual DbSet<TaxPreparer> TaxPreparers { get; set; }
        public virtual DbSet<PreparerNote> PreparerNotes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
